import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: { flex: 1, padding: 16 },
  content: { gap: 12, paddingBottom: 28 },
  heroCard: { alignItems: 'center', backgroundColor: '#FFFFFF', borderColor: '#E2E8F0', borderRadius: 20, borderWidth: 1, flexDirection: 'row', gap: 14, padding: 18 },
  heroIcon: { alignItems: 'center', backgroundColor: '#DBEAFE', borderRadius: 14, height: 46, justifyContent: 'center', width: 46 },
  heroCopy: { flex: 1, gap: 4 },
  eyebrow: { color: '#2563EB', fontSize: 11, fontWeight: '800', letterSpacing: 1 },
  title: { color: '#0F172A', fontSize: 22, fontWeight: '800' },
  mutedText: { color: '#64748B', fontSize: 13, lineHeight: 18 },
  primaryButton: { alignItems: 'center', backgroundColor: '#2563EB', borderRadius: 10, flexDirection: 'row', gap: 7, paddingHorizontal: 12, paddingVertical: 10 },
  primaryButtonText: { color: '#FFFFFF', fontSize: 12, fontWeight: '800' },
  summaryRow: { flexDirection: 'row', gap: 10 },
  summaryCard: { backgroundColor: '#FFFFFF', borderColor: '#E2E8F0', borderRadius: 14, borderWidth: 1, flex: 1, padding: 14 },
  summaryValue: { color: '#0F172A', fontSize: 22, fontWeight: '800' },
  summaryLabel: { color: '#64748B', fontSize: 12, marginTop: 3 },
  domainCard: { backgroundColor: '#FFFFFF', borderColor: '#E2E8F0', borderRadius: 16, borderWidth: 1, gap: 12, padding: 16 },
  domainHeader: { alignItems: 'flex-start', flexDirection: 'row', gap: 10 },
  domainCopy: { flex: 1, gap: 4 },
  domainName: { color: '#0F172A', fontSize: 16, fontWeight: '800' },
  domainMeta: { color: '#64748B', fontSize: 12 },
  statusBadge: { borderRadius: 99, borderWidth: 1, paddingHorizontal: 9, paddingVertical: 4 },
  statusText: { fontSize: 11, fontWeight: '800' },
  checkGrid: { backgroundColor: '#F8FAFC', borderRadius: 10, gap: 6, padding: 12 },
  checkItem: { color: '#334155', fontSize: 12, fontWeight: '600' },
  domainActions: { flexDirection: 'row', gap: 10 },
  secondaryButton: { alignItems: 'center', borderColor: '#BFDBFE', borderRadius: 9, borderWidth: 1, flexDirection: 'row', gap: 6, paddingHorizontal: 11, paddingVertical: 8 },
  linkButton: { alignItems: 'center', flexDirection: 'row', gap: 6, paddingHorizontal: 8, paddingVertical: 8 },
  secondaryButtonText: { color: '#2563EB', fontSize: 12, fontWeight: '800' },
  loadingRow: { alignItems: 'center', flexDirection: 'row', gap: 10, justifyContent: 'center', padding: 18 },
  emptyCard: { backgroundColor: '#FFFFFF', borderColor: '#E2E8F0', borderRadius: 16, borderWidth: 1, gap: 6, padding: 18 },
  emptyTitle: { color: '#0F172A', fontSize: 16, fontWeight: '800' },
  errorCard: { backgroundColor: '#FEF2F2', borderColor: '#FECACA', borderRadius: 12, borderWidth: 1, padding: 12 },
  errorText: { color: '#B91C1C', fontSize: 12, lineHeight: 17 },
  deniedCard: { backgroundColor: '#FFFFFF', borderColor: '#E2E8F0', borderRadius: 16, borderWidth: 1, gap: 8, padding: 18 },
  deniedTitle: { color: '#0F172A', fontSize: 18, fontWeight: '800' },
});
