import { Platform, StyleSheet } from 'react-native';

const cardShadow = Platform.select({
  ios: {
    shadowColor: '#0F172A',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.06,
    shadowRadius: 16,
  },
  android: { elevation: 3 },
  web: { boxShadow: '0 6px 18px rgba(15,23,42,0.08)' },
});

const labelShadow = Platform.select({
  ios: {
    shadowColor: '#0F172A',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.08,
    shadowRadius: 10,
  },
  android: { elevation: 2 },
  web: { boxShadow: '0 3px 12px rgba(15,23,42,0.1)' },
});

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  scroll: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: 16,
    paddingTop: 14,
    paddingBottom: 28,
    alignItems: 'center',
  },
  shell: {
    width: '100%',
    maxWidth: 1120,
    gap: 16,
  },
  shellWide: {
    flexDirection: 'row',
    alignItems: 'flex-start',
  },
  panel: {
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    padding: 18,
    ...cardShadow,
  },
  formPanel: {
    flex: 1.05,
  },
  previewPanel: {
    flex: 0.95,
  },
  panelTitle: {
    fontSize: 18,
    fontWeight: '800',
    color: '#0F172A',
    marginBottom: 6,
  },
  panelSub: {
    fontSize: 13,
    lineHeight: 19,
    color: '#64748B',
    marginBottom: 18,
  },
  fieldBlock: {
    marginBottom: 15,
  },
  fieldLabel: {
    fontSize: 12,
    fontWeight: '800',
    color: '#475569',
    marginBottom: 8,
    textTransform: 'uppercase',
    letterSpacing: 0.3,
  },
  inputWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 14,
    backgroundColor: '#F8FAFC',
    paddingHorizontal: 12,
    paddingVertical: Platform.OS === 'web' ? 11 : 4,
  },
  input: {
    flex: 1,
    minHeight: 32,
    padding: 0,
    fontSize: 15,
    color: '#0F172A',
  },
  textArea: {
    minHeight: 96,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 14,
    backgroundColor: '#F8FAFC',
    paddingHorizontal: 12,
    paddingVertical: 11,
    fontSize: 15,
    lineHeight: 21,
    color: '#0F172A',
    textAlignVertical: 'top',
  },
  labelTextInput: {
    minHeight: 160,
    fontSize: 16,
    lineHeight: 23,
    fontWeight: '700',
  },
  templateCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    borderWidth: 1,
    borderColor: '#DBEAFE',
    borderRadius: 16,
    backgroundColor: '#EFF6FF',
    padding: 14,
    marginBottom: 16,
  },
  templateIcon: {
    width: 42,
    height: 42,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#DBEAFE',
  },
  templateText: {
    flex: 1,
  },
  templateTitle: {
    fontSize: 15,
    fontWeight: '800',
    color: '#0F172A',
    lineHeight: 20,
  },
  templateDescription: {
    fontSize: 12,
    lineHeight: 17,
    color: '#64748B',
    marginTop: 2,
  },
  selectedProduct: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginTop: 8,
    borderWidth: 1,
    borderColor: '#BBF7D0',
    borderRadius: 12,
    backgroundColor: '#F0FDF4',
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  selectedProductText: {
    flex: 1,
    fontSize: 13,
    fontWeight: '700',
    color: '#166534',
  },
  resultList: {
    marginTop: 6,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 14,
    backgroundColor: '#FFFFFF',
  },
  resultItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingHorizontal: 13,
    paddingVertical: 11,
    borderBottomWidth: 1,
    borderBottomColor: '#F1F5F9',
  },
  resultName: {
    flex: 1,
    fontSize: 14,
    fontWeight: '700',
    color: '#0F172A',
  },
  resultTextBlock: {
    flex: 1,
  },
  resultMeta: {
    fontSize: 11,
    color: '#64748B',
    marginTop: 2,
  },
  emptyResult: {
    marginTop: 6,
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 12,
    backgroundColor: '#F8FAFC',
  },
  emptyResultText: {
    fontSize: 12,
    color: '#64748B',
  },
  actionRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginTop: 2,
  },
  primaryButton: {
    minHeight: 44,
    borderRadius: 14,
    paddingHorizontal: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  secondaryButton: {
    minHeight: 44,
    borderRadius: 14,
    paddingHorizontal: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    backgroundColor: '#FFFFFF',
  },
  buttonText: {
    fontSize: 13,
    fontWeight: '800',
  },
  previewWrap: {
    alignItems: 'center',
    marginBottom: 18,
  },
  labelPreview: {
    width: '100%',
    maxWidth: 360,
    minHeight: 168,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#CBD5E1',
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 20,
    paddingVertical: 18,
    alignItems: 'center',
    justifyContent: 'center',
    ...labelShadow,
  },
  labelPreviewMuted: {
    opacity: 0.72,
  },
  labelProduct: {
    fontSize: 23,
    lineHeight: 28,
    fontWeight: '900',
    color: '#0F172A',
    textAlign: 'center',
    textTransform: 'uppercase',
  },
  labelDate: {
    fontSize: 19,
    lineHeight: 24,
    fontWeight: '900',
    color: '#0F172A',
    textAlign: 'center',
    marginTop: 12,
  },
  labelFreeText: {
    fontSize: 14,
    lineHeight: 19,
    fontWeight: '700',
    color: '#334155',
    textAlign: 'center',
    marginTop: 14,
  },
  helperText: {
    fontSize: 12,
    lineHeight: 18,
    color: '#64748B',
    marginTop: 10,
    textAlign: 'center',
  },
});

export default styles;
