import {StyleSheet} from 'react-native';

export default StyleSheet.create({
  container: {
    backgroundColor: '#F8FAFC',
    flex: 1,
    padding: 16,
  },
  header: {
    marginBottom: 14,
  },
  title: {
    color: '#0F172A',
    fontSize: 22,
    fontWeight: '800',
  },
  subtitle: {
    color: '#64748B',
    fontSize: 13,
    fontWeight: '600',
    marginTop: 4,
  },
  appTypeSelector: {
    alignSelf: 'flex-start',
    marginBottom: 14,
    minWidth: 190,
    position: 'relative',
    zIndex: 2,
  },
  selectorLabel: {
    color: '#64748B',
    fontSize: 11,
    fontWeight: '800',
    marginBottom: 5,
  },
  appTypeSelectButton: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderColor: '#D8E0EA',
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 10,
    justifyContent: 'space-between',
    paddingHorizontal: 12,
    paddingVertical: 9,
  },
  appTypeSelectText: {
    color: '#0F172A',
    fontSize: 13,
    fontWeight: '800',
  },
  appTypeOptions: {
    backgroundColor: '#FFFFFF',
    borderColor: '#D8E0EA',
    borderRadius: 8,
    borderWidth: 1,
    left: 0,
    marginTop: 4,
    overflow: 'hidden',
    position: 'absolute',
    right: 0,
    top: 59,
  },
  appTypeOption: {
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  appTypeOptionActive: {
    backgroundColor: '#EFF6FF',
  },
  appTypeOptionText: {
    color: '#334155',
    fontSize: 13,
    fontWeight: '800',
  },
  appTypeOptionTextActive: {
    color: '#1D4ED8',
  },
  list: {
    gap: 12,
    paddingBottom: 20,
  },
  row: {
    backgroundColor: '#FFFFFF',
    borderColor: '#D8E0EA',
    borderRadius: 8,
    borderWidth: 1,
    padding: 14,
  },
  rowDisabled: {
    opacity: 0.62,
  },
  rowHeader: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    gap: 12,
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  rowTitleGroup: {
    flex: 1,
    gap: 3,
  },
  menuTitle: {
    color: '#0F172A',
    fontSize: 15,
    fontWeight: '800',
  },
  menuMeta: {
    color: '#64748B',
    fontSize: 12,
    fontWeight: '600',
  },
  enabledButton: {
    alignItems: 'center',
    backgroundColor: '#F1F5F9',
    borderRadius: 8,
    flexDirection: 'row',
    gap: 6,
    paddingHorizontal: 10,
    paddingVertical: 7,
  },
  enabledButtonActive: {
    backgroundColor: '#16A34A',
  },
  enabledText: {
    color: '#64748B',
    fontSize: 12,
    fontWeight: '800',
  },
  enabledTextActive: {
    color: '#FFFFFF',
  },
  linkGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  linkButton: {
    alignItems: 'center',
    backgroundColor: '#F8FAFC',
    borderColor: '#E2E8F0',
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 7,
    minHeight: 34,
    paddingHorizontal: 10,
  },
  linkButtonActive: {
    backgroundColor: '#EFF6FF',
    borderColor: '#93C5FD',
  },
  linkText: {
    color: '#64748B',
    fontSize: 12,
    fontWeight: '700',
  },
  linkTextActive: {
    color: '#1D4ED8',
  },
  centerState: {
    alignItems: 'center',
    flex: 1,
    gap: 8,
    justifyContent: 'center',
    padding: 24,
  },
  centerTitle: {
    color: '#0F172A',
    fontSize: 18,
    fontWeight: '800',
  },
  centerText: {
    color: '#64748B',
    fontSize: 13,
    fontWeight: '700',
    textAlign: 'center',
  },
  emptyState: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderColor: '#D8E0EA',
    borderRadius: 8,
    borderWidth: 1,
    padding: 22,
  },
  pagination: {
    alignItems: 'center',
    borderTopColor: '#E2E8F0',
    borderTopWidth: 1,
    flexDirection: 'row',
    gap: 10,
    justifyContent: 'center',
    paddingTop: 12,
  },
  pageButton: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderColor: '#CBD5E1',
    borderRadius: 8,
    borderWidth: 1,
    height: 34,
    justifyContent: 'center',
    width: 38,
  },
  pageButtonDisabled: {
    backgroundColor: '#F1F5F9',
  },
  pageText: {
    color: '#334155',
    fontSize: 13,
    fontWeight: '800',
  },
});
