import {StyleSheet} from 'react-native';

export default StyleSheet.create({
  container: {
    backgroundColor: '#F8FAFC',
    flex: 1,
    padding: 16,
  },
  header: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    gap: 12,
    justifyContent: 'space-between',
    marginBottom: 14,
  },
  title: {
    color: '#0F172A',
    fontSize: 22,
    fontWeight: '800',
  },
  subtitle: {
    color: '#64748B',
    fontSize: 13,
    fontWeight: '600',
    marginTop: 4,
  },
  appTypeSelector: {
    alignSelf: 'flex-start',
    marginBottom: 14,
    minWidth: 190,
    position: 'relative',
    zIndex: 2,
  },
  selectorLabel: {
    color: '#64748B',
    fontSize: 11,
    fontWeight: '800',
    marginBottom: 5,
  },
  appTypeSelectButton: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderColor: '#D8E0EA',
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 10,
    justifyContent: 'space-between',
    paddingHorizontal: 12,
    paddingVertical: 9,
  },
  appTypeSelectText: {
    color: '#0F172A',
    fontSize: 13,
    fontWeight: '800',
  },
  appTypeOptions: {
    backgroundColor: '#FFFFFF',
    borderColor: '#D8E0EA',
    borderRadius: 8,
    borderWidth: 1,
    left: 0,
    marginTop: 4,
    overflow: 'hidden',
    position: 'absolute',
    right: 0,
    top: 59,
  },
  appTypeOption: {
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  appTypeOptionActive: {
    backgroundColor: '#EFF6FF',
  },
  appTypeOptionText: {
    color: '#334155',
    fontSize: 13,
    fontWeight: '800',
  },
  appTypeOptionTextActive: {
    color: '#1D4ED8',
  },
  list: {
    gap: 14,
    paddingBottom: 24,
  },
  categoryBlock: {
    backgroundColor: '#FFFFFF',
    borderColor: '#D8E0EA',
    borderRadius: 8,
    borderWidth: 1,
    overflow: 'hidden',
  },
  categoryHeader: {
    alignItems: 'center',
    backgroundColor: '#F1F5F9',
    borderBottomColor: '#E2E8F0',
    borderBottomWidth: 1,
    flexDirection: 'row',
    gap: 12,
    justifyContent: 'space-between',
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  categoryPreview: {
    alignItems: 'center',
    flex: 1,
    flexDirection: 'row',
    gap: 9,
    minWidth: 0,
  },
  categoryTitle: {
    color: '#0F172A',
    flexShrink: 1,
    fontSize: 16,
    fontWeight: '800',
  },
  categoryActions: {
    alignItems: 'center',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    justifyContent: 'flex-end',
  },
  categoryFields: {
    alignItems: 'center',
    borderBottomColor: '#E2E8F0',
    borderBottomWidth: 1,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    padding: 12,
  },
  menuList: {
    gap: 10,
    padding: 12,
  },
  menuRow: {
    borderColor: '#E2E8F0',
    borderRadius: 8,
    borderWidth: 1,
    gap: 12,
    padding: 12,
  },
  rowDisabled: {
    opacity: 0.62,
  },
  menuHeader: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    gap: 12,
    justifyContent: 'space-between',
  },
  menuPreview: {
    alignItems: 'center',
    flex: 1,
    flexDirection: 'row',
    gap: 9,
    minWidth: 0,
  },
  rowTitleGroup: {
    flex: 1,
    gap: 3,
    minWidth: 0,
  },
  menuTitle: {
    color: '#0F172A',
    fontSize: 15,
    fontWeight: '800',
  },
  menuMeta: {
    color: '#64748B',
    fontSize: 12,
    fontWeight: '600',
  },
  formGrid: {
    alignItems: 'flex-end',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  field: {
    flexGrow: 1,
    minWidth: 210,
  },
  fieldSmall: {
    flexGrow: 1,
    minWidth: 130,
  },
  fieldTiny: {
    width: 82,
  },
  fieldLabel: {
    color: '#64748B',
    fontSize: 11,
    fontWeight: '800',
    marginBottom: 5,
  },
  input: {
    backgroundColor: '#FFFFFF',
    borderColor: '#CBD5E1',
    borderRadius: 8,
    borderWidth: 1,
    color: '#0F172A',
    fontSize: 13,
    fontWeight: '700',
    minHeight: 38,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  compactInput: {
    backgroundColor: '#FFFFFF',
    borderColor: '#CBD5E1',
    borderRadius: 8,
    borderWidth: 1,
    color: '#0F172A',
    fontSize: 13,
    fontWeight: '700',
    minHeight: 38,
    minWidth: 120,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  selectField: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderColor: '#CBD5E1',
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 8,
    justifyContent: 'space-between',
    minHeight: 38,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  selectText: {
    color: '#0F172A',
    flexShrink: 1,
    fontSize: 13,
    fontWeight: '700',
  },
  enabledButton: {
    alignItems: 'center',
    backgroundColor: '#F1F5F9',
    borderRadius: 8,
    flexDirection: 'row',
    gap: 6,
    paddingHorizontal: 10,
    paddingVertical: 7,
  },
  enabledButtonActive: {
    backgroundColor: '#16A34A',
  },
  enabledText: {
    color: '#64748B',
    fontSize: 12,
    fontWeight: '800',
  },
  enabledTextActive: {
    color: '#FFFFFF',
  },
  linkGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  linkButton: {
    alignItems: 'center',
    backgroundColor: '#F8FAFC',
    borderColor: '#E2E8F0',
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 7,
    minHeight: 34,
    paddingHorizontal: 10,
  },
  linkButtonActive: {
    backgroundColor: '#EFF6FF',
    borderColor: '#93C5FD',
  },
  linkText: {
    color: '#64748B',
    fontSize: 12,
    fontWeight: '700',
  },
  linkTextActive: {
    color: '#1D4ED8',
  },
  primaryButton: {
    alignItems: 'center',
    backgroundColor: '#2563EB',
    borderRadius: 8,
    flexDirection: 'row',
    gap: 7,
    minHeight: 38,
    paddingHorizontal: 12,
  },
  primaryButtonText: {
    color: '#FFFFFF',
    fontSize: 13,
    fontWeight: '800',
  },
  secondaryButton: {
    alignItems: 'center',
    backgroundColor: '#EFF6FF',
    borderColor: '#BFDBFE',
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 6,
    minHeight: 34,
    paddingHorizontal: 10,
  },
  secondaryButtonText: {
    color: '#2563EB',
    fontSize: 12,
    fontWeight: '800',
  },
  saveButton: {
    alignItems: 'center',
    alignSelf: 'flex-start',
    backgroundColor: '#0F766E',
    borderRadius: 8,
    flexDirection: 'row',
    gap: 7,
    minHeight: 36,
    paddingHorizontal: 12,
  },
  saveButtonText: {
    color: '#FFFFFF',
    fontSize: 13,
    fontWeight: '800',
  },
  iconButton: {
    alignItems: 'center',
    backgroundColor: '#F1F5F9',
    borderRadius: 8,
    height: 34,
    justifyContent: 'center',
    width: 34,
  },
  addPanel: {
    backgroundColor: '#FFFFFF',
    borderColor: '#BFDBFE',
    borderRadius: 8,
    borderWidth: 1,
    gap: 12,
    marginBottom: 14,
    padding: 12,
  },
  addPanelHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  sectionTitle: {
    color: '#0F172A',
    fontSize: 15,
    fontWeight: '800',
  },
  centerState: {
    alignItems: 'center',
    flex: 1,
    gap: 8,
    justifyContent: 'center',
    padding: 24,
  },
  centerTitle: {
    color: '#0F172A',
    fontSize: 18,
    fontWeight: '800',
  },
  centerText: {
    color: '#64748B',
    fontSize: 13,
    fontWeight: '700',
    textAlign: 'center',
  },
  emptyState: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderColor: '#D8E0EA',
    borderRadius: 8,
    borderWidth: 1,
    padding: 22,
  },
  modalOverlay: {
    alignItems: 'center',
    backgroundColor: 'rgba(15, 23, 42, 0.38)',
    flex: 1,
    justifyContent: 'center',
    padding: 18,
  },
  modalPanel: {
    backgroundColor: '#FFFFFF',
    borderRadius: 8,
    maxHeight: '82%',
    maxWidth: 560,
    padding: 14,
    width: '100%',
  },
  modalHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  modalTitle: {
    color: '#0F172A',
    fontSize: 16,
    fontWeight: '800',
  },
  modalSearch: {
    backgroundColor: '#F8FAFC',
    borderColor: '#CBD5E1',
    borderRadius: 8,
    borderWidth: 1,
    color: '#0F172A',
    fontSize: 13,
    fontWeight: '700',
    marginBottom: 10,
    minHeight: 38,
    paddingHorizontal: 10,
  },
  modalOptions: {
    gap: 6,
  },
  optionRow: {
    borderColor: '#E2E8F0',
    borderRadius: 8,
    borderWidth: 1,
    paddingHorizontal: 10,
    paddingVertical: 9,
  },
  optionRowActive: {
    backgroundColor: '#EFF6FF',
    borderColor: '#93C5FD',
  },
  optionText: {
    color: '#0F172A',
    fontSize: 13,
    fontWeight: '800',
  },
  optionTextActive: {
    color: '#1D4ED8',
  },
  optionCaption: {
    color: '#64748B',
    fontSize: 12,
    fontWeight: '600',
    marginTop: 2,
  },
});
