import { Platform, StyleSheet } from 'react-native';

const cardShadow = Platform.select({
  ios: {
    shadowColor: '#1a1a1a',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.08,
    shadowRadius: 16,
  },
  android: { elevation: 3 },
  web: { boxShadow: '0 8px 24px rgba(15,23,42,0.08)' },
});

const themeCardShadow = Platform.select({
  ios: {
    shadowColor: '#0f172a',
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.12,
    shadowRadius: 22,
  },
  android: { elevation: 5 },
  web: { boxShadow: '0 14px 32px rgba(15,23,42,0.12)' },
});

const styles = StyleSheet.create({
  root: { flex: 1 },
  scroll: { padding: 16, paddingBottom: 40, gap: 16 },
  toolbar: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  createButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 12,
  },
  createButtonText: {
    color: '#FFFFFF',
    fontSize: 13,
    fontWeight: '800',
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: '800',
    color: '#1a1a1a',
  },
  sectionText: {
    fontSize: 13,
    lineHeight: 20,
    color: '#777777',
    marginTop: 4,
  },
  loadingWrap: {
    minHeight: 220,
    alignItems: 'center',
    justifyContent: 'center',
  },
  emptyCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    padding: 22,
    alignItems: 'center',
    gap: 10,
    ...cardShadow,
  },
  emptyTitle: {
    fontSize: 16,
    fontWeight: '800',
    color: '#1a1a1a',
    textAlign: 'center',
  },
  emptyText: {
    fontSize: 13,
    lineHeight: 20,
    color: '#777777',
    textAlign: 'center',
  },
  themeList: { gap: 28 },
  themeCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    padding: 16,
    gap: 14,
    ...themeCardShadow,
  },
  themeRowTop: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: 12,
  },
  themeTitleWrap: {
    flex: 1,
    gap: 4,
  },
  themeName: {
    fontSize: 16,
    fontWeight: '800',
    color: '#1a1a1a',
  },
  themeActions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    justifyContent: 'flex-end',
  },
  actionButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#d7d7d7',
    backgroundColor: '#F8FAFC',
  },
  actionButtonText: {
    fontSize: 12,
    fontWeight: '800',
    color: '#1a1a1a',
  },
  themeMetaText: {
    fontSize: 12,
    color: '#777777',
    fontWeight: '700',
  },
  columnsRow: {
    flexDirection: 'row',
    alignItems: 'stretch',
    gap: 12,
  },
  themeColumn: {
    height: 420,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#e2e8f0',
    backgroundColor: '#F8FAFC',
    overflow: 'hidden',
  },
  themeColumnQuarter: {
    flex: 1,
  },
  themeColumnHalf: {
    flex: 2,
  },
  columnHeader: {
    minHeight: 44,
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#e2e8f0',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  columnHeaderTitleWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    minWidth: 0,
  },
  columnTitle: {
    flex: 1,
    minHeight: 16,
    fontSize: 12,
    fontWeight: '800',
    color: '#1a1a1a',
    textTransform: 'uppercase',
    letterSpacing: 0.4,
  },
  columnMeta: {
    fontSize: 12,
    fontWeight: '800',
    color: '#64748B',
  },
  columnMetaWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  columnRnwToggle: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 8,
    paddingVertical: 5,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: '#D7E1EC',
    backgroundColor: '#FFFFFF',
  },
  columnRnwToggleActive: {
    borderColor: '#2563EB',
    backgroundColor: '#EFF6FF',
  },
  columnRnwCheckbox: {
    width: 14,
    height: 14,
    borderRadius: 4,
    borderWidth: 1,
    borderColor: '#94A3B8',
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  columnRnwCheckboxActive: {
    borderColor: '#2563EB',
    backgroundColor: '#2563EB',
  },
  columnRnwLabel: {
    fontSize: 11,
    fontWeight: '800',
    color: '#64748B',
    textTransform: 'uppercase',
    letterSpacing: 0.3,
  },
  columnRnwLabelActive: {
    color: '#1D4ED8',
  },
  columnFilterButton: {
    width: 22,
    height: 22,
    borderRadius: 7,
    borderWidth: 1,
    borderColor: '#D7E1EC',
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  columnFilterButtonActive: {
    borderColor: '#0F172A',
    backgroundColor: '#334155',
  },
  columnScroll: {
    flex: 1,
  },
  columnBody: {
    padding: 10,
    gap: 10,
  },
  previewColumnBody: {
    padding: 10,
    gap: 10,
  },
  columnHeaderSearchWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 10,
    height: 32,
    minWidth: 180,
    flex: 1,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#D7E1EC',
    backgroundColor: '#FFFFFF',
  },
  columnHeaderSearchWrapCompact: {
    minWidth: 0,
    flex: 1,
  },
  columnHeaderSearchInput: {
    flex: 1,
    height: '100%',
    fontSize: 12,
    fontWeight: '600',
    color: '#1A1A1A',
    outlineStyle: 'none',
    ...Platform.select({
      web: {
        outlineWidth: 0,
        boxShadow: 'none',
      },
    }),
  },
  objectPreviewCard: {
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#d7e1ec',
    backgroundColor: '#FFFFFF',
    overflow: 'hidden',
  },
  objectPreviewCardFilled: {
    borderColor: '#16A34A',
    borderWidth: 2,
  },
  objectPreviewHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#e2e8f0',
    backgroundColor: '#F8FAFC',
  },
  objectPreviewTitle: {
    flex: 1,
    fontSize: 12,
    fontWeight: '800',
    color: '#1a1a1a',
    textTransform: 'uppercase',
    letterSpacing: 0.4,
  },
  objectPreviewMeta: {
    fontSize: 11,
    fontWeight: '800',
    color: '#64748B',
  },
  objectPreviewBody: {
    padding: 12,
  },
  previewStack: {
    gap: 8,
  },
  previewRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  previewRowWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: 8,
  },
  previewButton: {
    minHeight: 34,
    borderRadius: 10,
    borderWidth: 1,
    paddingHorizontal: 12,
    paddingVertical: 8,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    flex: 1,
  },
  previewButtonDisabled: {
    flex: 0,
  },
  previewButtonText: {
    fontSize: 11,
    fontWeight: '800',
  },
  previewIconRow: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: 8,
  },
  previewIconBubble: {
    width: 34,
    height: 34,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  previewChoiceRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  previewChoiceTarget: {
    padding: 2,
    borderRadius: 8,
  },
  previewChoiceTextTarget: {
    flex: 1,
    paddingVertical: 2,
    borderRadius: 8,
  },
  previewChoiceText: {
    fontSize: 12,
    fontWeight: '700',
  },
  previewCheckbox: {
    width: 20,
    height: 20,
    borderRadius: 6,
    borderWidth: 1.5,
    alignItems: 'center',
    justifyContent: 'center',
  },
  previewRadio: {
    width: 20,
    height: 20,
    borderRadius: 999,
    borderWidth: 1.5,
    alignItems: 'center',
    justifyContent: 'center',
  },
  previewRadioDot: {
    width: 8,
    height: 8,
    borderRadius: 999,
  },
  previewBar: {
    minHeight: 44,
    borderRadius: 12,
    borderWidth: 1,
    paddingHorizontal: 12,
    paddingVertical: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  previewBarSide: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  previewBarTitle: {
    fontSize: 12,
    fontWeight: '800',
  },
  previewInnerCard: {
    borderRadius: 12,
    borderWidth: 1,
    overflow: 'hidden',
  },
  previewInnerCardHeader: {
    minHeight: 38,
    paddingHorizontal: 12,
    paddingVertical: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  previewInnerCardContent: {
    padding: 12,
  },
  previewInnerCardTitle: {
    fontSize: 12,
    fontWeight: '800',
  },
  previewParagraph: {
    fontSize: 11,
    lineHeight: 16,
    fontWeight: '600',
  },
  previewPill: {
    minHeight: 30,
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: 10,
    paddingVertical: 6,
    alignItems: 'center',
    justifyContent: 'center',
  },
  previewPillText: {
    fontSize: 11,
    fontWeight: '800',
  },
  previewField: {
    minHeight: 38,
    borderRadius: 10,
    borderWidth: 1,
    paddingHorizontal: 12,
    paddingVertical: 9,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  previewFieldText: {
    flex: 1,
    fontSize: 11,
    fontWeight: '700',
  },
  previewHeadline: {
    fontSize: 13,
    fontWeight: '800',
  },
  previewInlineLink: {
    fontSize: 11,
    fontWeight: '800',
  },
  previewListItem: {
    minHeight: 36,
    borderRadius: 10,
    borderWidth: 1,
    paddingHorizontal: 10,
    paddingVertical: 8,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  previewListText: {
    fontSize: 11,
    fontWeight: '700',
  },
  previewOverlayShell: {
    minHeight: 84,
    borderRadius: 12,
    overflow: 'hidden',
    justifyContent: 'center',
  },
  previewOverlayBackdrop: {
    ...StyleSheet.absoluteFillObject,
  },
  previewOverlayCard: {
    marginHorizontal: 18,
    borderRadius: 12,
    borderWidth: 1,
    paddingHorizontal: 12,
    paddingVertical: 14,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  previewSwitch: {
    width: 40,
    height: 24,
    borderRadius: 999,
    padding: 3,
    justifyContent: 'center',
  },
  previewSwitchThumb: {
    width: 18,
    height: 18,
    borderRadius: 999,
  },
  previewToast: {
    minHeight: 34,
    borderRadius: 10,
    borderWidth: 1,
    paddingHorizontal: 10,
    paddingVertical: 8,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  previewToastText: {
    fontSize: 11,
    fontWeight: '700',
  },
  previewDivider: {
    height: 1,
    width: '100%',
  },
  previewSurfaceCard: {
    borderRadius: 12,
    borderWidth: 1,
    padding: 12,
    gap: 8,
  },
  previewTokenGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  previewTokenCard: {
    width: '31%',
    minWidth: 82,
    gap: 6,
  },
  previewTokenSwatch: {
    height: 30,
    borderRadius: 10,
    borderWidth: 1,
  },
  previewTokenSwatchEmpty: {
    backgroundColor: '#F8FAFC',
    borderColor: '#CBD5E1',
  },
  transparentPreviewTokenSwatch: {
    backgroundColor: '#FFFFFF',
    borderColor: '#94A3B8',
    borderStyle: 'dashed',
  },
  previewTokenLabel: {
    fontSize: 10,
    fontWeight: '700',
    color: '#475569',
  },
  colorListItem: {
    position: 'relative',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    padding: 10,
    paddingRight: 66,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#d7e1ec',
    backgroundColor: '#FFFFFF',
  },
  relatedColorListItem: {
    borderWidth: 3,
    borderColor: '#334155',
  },
  unexpectedColorListItem: {
    borderColor: '#DC2626',
    borderWidth: 2,
  },
  colorEditButton: {
    position: 'absolute',
    top: 8,
    right: 8,
    width: 22,
    height: 22,
    borderRadius: 7,
    borderWidth: 1,
    borderColor: '#d7e1ec',
    backgroundColor: '#F8FAFC',
    alignItems: 'center',
    justifyContent: 'center',
  },
  colorDeleteButton: {
    position: 'absolute',
    top: 8,
    right: 36,
    width: 22,
    height: 22,
    borderRadius: 7,
    borderWidth: 1,
    borderColor: '#d7e1ec',
    backgroundColor: '#F8FAFC',
    alignItems: 'center',
    justifyContent: 'center',
  },
  colorSwatch: {
    width: 18,
    height: 18,
    borderRadius: 6,
    borderWidth: 1,
  },
  transparentColorSwatch: {
    backgroundColor: '#FFFFFF',
    borderColor: '#94A3B8',
    borderStyle: 'dashed',
  },
  missingColorSwatch: {
    backgroundColor: '#F8FAFC',
    borderColor: '#CBD5E1',
  },
  colorListKey: {
    fontSize: 12,
    fontWeight: '800',
    color: '#1a1a1a',
  },
  colorListValue: {
    fontSize: 11,
    fontWeight: '700',
    color: '#64748B',
    marginTop: 2,
  },
  iconButton: {
    width: 38,
    height: 38,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#cccccc',
    backgroundColor: '#F8FAFC',
  },
  backdrop: {
    flex: 1,
    backgroundColor: 'rgba(15,23,42,0.48)',
    justifyContent: 'flex-end',
  },
  modalSheet: {
    backgroundColor: '#FFFFFF',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    minHeight: 260,
    maxHeight: '92%',
    padding: 16,
    gap: 14,
    ...cardShadow,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 12,
  },
  modalTitle: {
    flex: 1,
    fontSize: 18,
    fontWeight: '800',
    color: '#1a1a1a',
  },
  modalSubtitle: {
    fontSize: 13,
    lineHeight: 20,
    color: '#777777',
  },
  formField: { gap: 8 },
  formLabel: {
    fontSize: 12,
    fontWeight: '800',
    color: '#475569',
    textTransform: 'uppercase',
    letterSpacing: 0.4,
  },
  textInput: {
    height: 46,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#cccccc',
    paddingHorizontal: 12,
    fontSize: 14,
    fontWeight: '600',
    color: '#1a1a1a',
    backgroundColor: '#FFFFFF',
  },
  helperText: {
    fontSize: 12,
    lineHeight: 18,
    color: '#777777',
  },
  colorEditor: {
    gap: 10,
    padding: 14,
    borderRadius: 16,
    backgroundColor: '#F8FAFC',
    borderWidth: 1,
    borderColor: '#cccccc',
  },
  colorEditorHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 10,
  },
  colorEditorLabel: {
    fontSize: 14,
    fontWeight: '800',
    color: '#1a1a1a',
  },
  colorEditorLabelLarge: {
    fontSize: 18,
  },
  editorCloseButton: {
    width: 38,
    height: 38,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#D7E1EC',
    backgroundColor: '#F8FAFC',
  },
  swatchPicker: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  swatchPickerCard: {
    gap: 8,
    padding: 12,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#D7E1EC',
    backgroundColor: '#FFFFFF',
  },
  swatchPickerSection: {
    gap: 8,
  },
  swatchPickerLabel: {
    fontSize: 11,
    fontWeight: '800',
    color: '#475569',
    textTransform: 'uppercase',
    letterSpacing: 0.4,
  },
  swatchPickerEmpty: {
    fontSize: 12,
    fontWeight: '700',
    color: '#94A3B8',
  },
  pickerButton: {
    width: 30,
    height: 30,
    borderRadius: 10,
    borderWidth: 2,
    borderColor: 'transparent',
  },
  pickerButtonWrap: {
    position: 'relative',
  },
  pickerButtonActive: {
    borderColor: '#1a1a1a',
  },
  pickerTooltip: {
    position: 'absolute',
    bottom: 36,
    left: '50%',
    transform: [{ translateX: -36 }],
    backgroundColor: '#0F172A',
    borderRadius: 8,
    paddingHorizontal: 8,
    paddingVertical: 6,
    zIndex: 10,
    minWidth: 72,
  },
  pickerTooltipText: {
    fontSize: 11,
    fontWeight: '700',
    color: '#FFFFFF',
    textAlign: 'center',
  },
  colorInputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    flex: 1.2,
  },
  colorInput: {
    flex: 1,
    height: 42,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#cccccc',
    paddingHorizontal: 12,
    fontSize: 14,
    fontWeight: '700',
    color: '#1a1a1a',
    backgroundColor: '#FFFFFF',
  },
  colorHint: {
    fontSize: 12,
    fontWeight: '700',
    color: '#777777',
  },
  colorControlsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  transparentToggle: {
    minHeight: 42,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#CBD5E1',
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    flexShrink: 0,
  },
  transparentToggleActive: {
    borderWidth: 2,
    borderColor: '#0F172A',
  },
  transparentToggleBox: {
    width: 20,
    height: 20,
    borderRadius: 6,
    borderWidth: 1.5,
    borderColor: '#94A3B8',
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  transparentToggleBoxActive: {
    borderColor: '#0F172A',
    backgroundColor: '#E2E8F0',
  },
  transparentToggleLabel: {
    fontSize: 13,
    fontWeight: '700',
    color: '#1A1A1A',
  },
  opacityEditor: {
    gap: 8,
  },
  opacityEditorInline: {
    flex: 1,
    minHeight: 42,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#CBD5E1',
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  opacityEditorInlineValue: {
    fontSize: 12,
    fontWeight: '800',
    color: '#1a1a1a',
    minWidth: 40,
    textAlign: 'right',
  },
  opacityEditorDisabled: {
    opacity: 0.45,
  },
  opacityEditorHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  opacityEditorLabel: {
    fontSize: 12,
    fontWeight: '800',
    color: '#475569',
    textTransform: 'uppercase',
    letterSpacing: 0.4,
  },
  opacityEditorValue: {
    fontSize: 12,
    fontWeight: '800',
    color: '#1a1a1a',
  },
  opacitySliderArea: {
    height: 24,
    justifyContent: 'center',
  },
  opacitySliderAreaInline: {
    flex: 1,
    height: 24,
    justifyContent: 'center',
  },
  opacitySliderTrack: {
    height: 6,
    borderRadius: 999,
    backgroundColor: '#D7E1EC',
  },
  opacitySliderFill: {
    position: 'absolute',
    left: 0,
    height: 6,
    borderRadius: 999,
    backgroundColor: '#0F172A',
  },
  opacitySliderThumb: {
    position: 'absolute',
    top: 2,
    width: 20,
    height: 20,
    borderRadius: 999,
    backgroundColor: '#FFFFFF',
    borderWidth: 2,
    borderColor: '#0F172A',
  },
  opacitySliderThumbDisabled: {
    borderColor: '#94A3B8',
  },
  modalActions: {
    flexDirection: 'row',
    gap: 10,
    paddingTop: 8,
  },
  secondaryButton: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 14,
    borderRadius: 12,
    borderWidth: 1.5,
    borderColor: '#cccccc',
    backgroundColor: '#FFFFFF',
  },
  secondaryButtonText: {
    fontSize: 14,
    fontWeight: '800',
    color: '#1a1a1a',
  },
  primaryButton: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 14,
    borderRadius: 12,
  },
  primaryButtonText: {
    fontSize: 14,
    fontWeight: '800',
    color: '#FFFFFF',
  },
});

export default styles;
