import { Platform, StyleSheet } from 'react-native';

const elevatedShadow = Platform.select({
  web: { boxShadow: '0 18px 60px rgba(15, 23, 42, 0.14)' },
  default: {
    shadowColor: '#0F172A',
    shadowOpacity: 0.12,
    shadowRadius: 24,
    shadowOffset: { width: 0, height: 14 },
    elevation: 8,
  },
});

const softShadow = Platform.select({
  web: { boxShadow: '0 10px 30px rgba(15, 23, 42, 0.10)' },
  default: {
    shadowColor: '#0F172A',
    shadowOpacity: 0.08,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 8 },
    elevation: 4,
  },
});

const styles = StyleSheet.create({
  root: { flex: 1 },
  ambientLayer: { ...StyleSheet.absoluteFillObject, overflow: 'hidden' },
  ambientOrbA: {
    position: 'absolute',
    top: -120,
    right: -60,
    width: 320,
    height: 320,
    borderRadius: 320,
  },
  ambientOrbB: {
    position: 'absolute',
    top: 180,
    left: -90,
    width: 240,
    height: 240,
    borderRadius: 240,
  },
  ambientOrbC: {
    position: 'absolute',
    bottom: 120,
    right: 80,
    width: 220,
    height: 220,
    borderRadius: 220,
  },

  controlsBar: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 18,
    paddingVertical: 12,
    borderBottomWidth: 1,
    gap: 14,
    flexWrap: 'wrap',
    zIndex: 5,
  },
  controlsInfo: { flex: 1, gap: 3, minWidth: 180 },
  controlsName: { fontSize: 15, fontWeight: '900' },
  controlsId: { fontSize: 11, fontWeight: '700' },
  controlsToggles: { flexDirection: 'row', alignItems: 'center', gap: 14, flexWrap: 'wrap' },
  toggleItem: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  toggleBox: {
    width: 16,
    height: 16,
    borderRadius: 4,
    borderWidth: 1.5,
    borderColor: '#94A3B8',
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  toggleBoxActive: { borderColor: '#2563EB', backgroundColor: '#2563EB' },
  toggleBoxGreen: { borderColor: '#16A34A', backgroundColor: '#16A34A' },
  toggleMark: { fontSize: 9, color: '#FFFFFF', fontWeight: '900', lineHeight: 10 },
  toggleLabel: { fontSize: 11, fontWeight: '800', color: '#334155' },
  toggleLabelActive: { color: '#1D4ED8' },
  toggleLabelGreen: { color: '#15803D' },

  scroll: { paddingHorizontal: 16, paddingVertical: 18, paddingBottom: 56 },
  shellFrame: {
    width: '100%',
    maxWidth: 1480,
    alignSelf: 'center',
    gap: 18,
  },
  previewWindow: {
    borderRadius: 30,
    borderWidth: 1,
    overflow: 'hidden',
    ...elevatedShadow,
  },
  topNav: {
    minHeight: 72,
    paddingHorizontal: 28,
    paddingVertical: 18,
    borderBottomWidth: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 18,
    flexWrap: 'wrap',
  },
  topNavBrand: { flexDirection: 'row', alignItems: 'center', gap: 14 },
  topNavBadge: {
    width: 42,
    height: 42,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  topNavTitleWrap: { gap: 2 },
  topNavEyebrow: {
    fontSize: 10,
    fontWeight: '800',
    textTransform: 'uppercase',
    letterSpacing: 1.2,
  },
  topNavTitle: { fontSize: 17, fontWeight: '900' },
  topNavLinks: { flexDirection: 'row', alignItems: 'center', gap: 18, flexWrap: 'wrap' },
  topNavLink: { fontSize: 12, fontWeight: '800' },

  workspaceRow: { padding: 18, gap: 18 },
  workspaceRowWide: { flexDirection: 'row', alignItems: 'stretch' },
  workspaceRowStack: { flexDirection: 'column' },
  sidebarColumn: { gap: 18 },
  sidebarColumnWide: { width: 286, flexShrink: 0 },
  sidebarColumnStack: { width: '100%' },
  mainColumn: { flex: 1, gap: 18 },

  sidebarSurface: {
    borderRadius: 24,
    borderWidth: 1,
    padding: 18,
    gap: 14,
    ...softShadow,
  },
  sidebarSectionLabel: {
    fontSize: 10,
    fontWeight: '900',
    textTransform: 'uppercase',
    letterSpacing: 1.1,
  },
  sidebarHero: { gap: 10 },
  sidebarHeroTitle: { fontSize: 20, fontWeight: '900', lineHeight: 24 },
  sidebarHeroText: { fontSize: 12, lineHeight: 18, fontWeight: '600' },
  sidebarMenuCard: {
    borderRadius: 20,
    borderWidth: 1,
    overflow: 'hidden',
  },
  sidebarMenuHeader: {
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderBottomWidth: 1,
  },
  sidebarMenuItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingHorizontal: 14,
    paddingVertical: 11,
    borderWidth: 1,
    borderRadius: 16,
  },
  sidebarMenuText: { flex: 1, fontSize: 12, fontWeight: '800' },
  sidebarMenuCaption: { fontSize: 11, fontWeight: '700' },
  sidebarMiniGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  sidebarMetricPill: {
    minWidth: 78,
    borderRadius: 16,
    borderWidth: 1,
    paddingHorizontal: 10,
    paddingVertical: 8,
    gap: 4,
  },
  sidebarMetricValue: { fontSize: 16, fontWeight: '900' },
  sidebarMetricLabel: { fontSize: 10, fontWeight: '800' },

  headerCard: {
    borderRadius: 24,
    borderWidth: 1,
    overflow: 'hidden',
    ...softShadow,
  },
  headerTop: {
    paddingHorizontal: 22,
    paddingVertical: 18,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 14,
    flexWrap: 'wrap',
  },
  headerTitleWrap: { flex: 1, gap: 5, minWidth: 220 },
  headerEyebrow: {
    fontSize: 10,
    fontWeight: '900',
    textTransform: 'uppercase',
    letterSpacing: 1.2,
  },
  headerTitle: { fontSize: 28, lineHeight: 32, fontWeight: '900' },
  headerSubtitle: { fontSize: 13, lineHeight: 19, fontWeight: '600' },
  toolbarRow: {
    borderTopWidth: 1,
    paddingHorizontal: 18,
    paddingVertical: 12,
    gap: 10,
  },
  toolbarMain: {
    minHeight: 48,
    borderRadius: 18,
    borderWidth: 1,
    paddingHorizontal: 16,
    paddingVertical: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
    flexWrap: 'wrap',
  },
  toolbarMeta: { flexDirection: 'row', alignItems: 'center', gap: 8, flexWrap: 'wrap' },
  toolbarMetaText: { fontSize: 11, fontWeight: '800' },
  tabRow: { flexDirection: 'row', alignItems: 'center', gap: 8, flexWrap: 'wrap' },
  tabPill: {
    minHeight: 36,
    borderRadius: 14,
    borderWidth: 1,
    paddingHorizontal: 14,
    paddingVertical: 8,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  tabText: { fontSize: 11, fontWeight: '800' },

  heroGrid: { gap: 18 },
  heroGridWide: { flexDirection: 'row' },
  heroGridStack: { flexDirection: 'column' },
  heroCopyCard: {
    flex: 1.15,
    borderRadius: 28,
    borderWidth: 1,
    padding: 26,
    gap: 18,
    ...softShadow,
  },
  heroVisualCard: {
    flex: 0.85,
    borderRadius: 28,
    borderWidth: 1,
    padding: 22,
    gap: 16,
    ...softShadow,
  },
  heroAnnouncement: {
    alignSelf: 'flex-start',
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: 12,
    paddingVertical: 8,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  heroAnnouncementText: { fontSize: 10, fontWeight: '900', textTransform: 'uppercase', letterSpacing: 1.1 },
  heroTitle: { fontSize: 46, lineHeight: 48, fontWeight: '900', maxWidth: 680 },
  heroText: { fontSize: 15, lineHeight: 23, fontWeight: '600', maxWidth: 620 },
  heroActions: { flexDirection: 'row', gap: 12, flexWrap: 'wrap' },
  heroButton: {
    minHeight: 50,
    borderRadius: 18,
    borderWidth: 1,
    paddingHorizontal: 18,
    paddingVertical: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  heroButtonText: { fontSize: 13, fontWeight: '900' },
  heroSubMeta: { flexDirection: 'row', alignItems: 'center', gap: 10, flexWrap: 'wrap' },
  heroLinkText: { fontSize: 12, fontWeight: '900' },
  badgeRow: { flexDirection: 'row', alignItems: 'center', gap: 8, flexWrap: 'wrap' },
  badgePill: {
    minHeight: 34,
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: 12,
    paddingVertical: 7,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  badgeText: { fontSize: 11, fontWeight: '900' },
  chipPill: {
    minHeight: 32,
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: 12,
    paddingVertical: 6,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 7,
  },
  chipText: { fontSize: 11, fontWeight: '800' },

  showcasePanel: {
    borderRadius: 22,
    borderWidth: 1,
    padding: 16,
    gap: 14,
  },
  showcaseTop: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 10 },
  showcaseTitle: { fontSize: 15, fontWeight: '900' },
  showcaseCaption: { fontSize: 11, lineHeight: 16, fontWeight: '700' },
  statsGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
  statCard: {
    minWidth: 104,
    flexGrow: 1,
    borderRadius: 18,
    borderWidth: 1,
    paddingHorizontal: 12,
    paddingVertical: 12,
    gap: 5,
  },
  statValue: { fontSize: 22, fontWeight: '900' },
  statLabel: { fontSize: 11, fontWeight: '800' },
  miniInsight: {
    borderRadius: 18,
    borderWidth: 1,
    padding: 14,
    gap: 10,
  },
  miniInsightRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 8 },
  miniInsightTitle: { fontSize: 12, fontWeight: '900' },
  miniInsightText: { fontSize: 11, lineHeight: 16, fontWeight: '700' },
  selectPreview: {
    minHeight: 42,
    borderRadius: 14,
    borderWidth: 1,
    paddingHorizontal: 12,
    paddingVertical: 9,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  selectPreviewText: { fontSize: 11, fontWeight: '800' },

  featureGrid: { gap: 18 },
  featureGridWide: { flexDirection: 'row' },
  featureGridStack: { flexDirection: 'column' },
  featureCard: {
    flex: 1,
    borderRadius: 24,
    borderWidth: 1,
    padding: 20,
    gap: 14,
    ...softShadow,
  },
  featureCardHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 10 },
  featureCardTitle: { fontSize: 16, fontWeight: '900' },
  featureCardText: { fontSize: 12, lineHeight: 18, fontWeight: '600' },
  featureIconBubble: {
    width: 38,
    height: 38,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
  },
  dividerLine: { height: 1, width: '100%' },
  textPaletteRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
  textTokenPill: {
    borderRadius: 12,
    paddingHorizontal: 10,
    paddingVertical: 8,
    minWidth: 86,
  },
  textTokenLabel: { fontSize: 11, fontWeight: '900' },

  contentGrid: { gap: 18 },
  contentGridWide: { flexDirection: 'row', alignItems: 'flex-start' },
  contentGridStack: { flexDirection: 'column' },
  contentStack: { flex: 1, gap: 18 },
  formCard: {
    flex: 1.05,
    borderRadius: 26,
    borderWidth: 1,
    padding: 20,
    gap: 16,
    ...softShadow,
  },
  listCard: {
    borderRadius: 24,
    borderWidth: 1,
    padding: 20,
    gap: 14,
    ...softShadow,
  },
  tableCard: {
    borderRadius: 24,
    borderWidth: 1,
    padding: 20,
    gap: 14,
    ...softShadow,
  },
  sectionHeaderRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 10 },
  sectionTitle: { fontSize: 16, fontWeight: '900' },
  sectionText: { fontSize: 12, lineHeight: 18, fontWeight: '600' },
  fieldStack: { gap: 8 },
  fieldLabel: { fontSize: 10, fontWeight: '900', textTransform: 'uppercase', letterSpacing: 0.8 },
  fieldBox: {
    minHeight: 48,
    borderRadius: 16,
    borderWidth: 1,
    paddingHorizontal: 14,
    paddingVertical: 11,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  fieldValue: { fontSize: 12, fontWeight: '700' },
  helperText: { fontSize: 11, lineHeight: 16, fontWeight: '700' },
  formTwoCols: { flexDirection: 'row', gap: 12, flexWrap: 'wrap' },
  formCol: { flex: 1, minWidth: 180, gap: 8 },
  controlRow: { flexDirection: 'row', alignItems: 'center', gap: 10, flexWrap: 'wrap' },
  checkboxBox: {
    width: 20,
    height: 20,
    borderRadius: 6,
    borderWidth: 1.5,
    alignItems: 'center',
    justifyContent: 'center',
  },
  checkboxMark: { fontSize: 11, fontWeight: '900' },
  radioBox: {
    width: 20,
    height: 20,
    borderRadius: 20,
    borderWidth: 1.5,
    alignItems: 'center',
    justifyContent: 'center',
  },
  radioDot: { width: 8, height: 8, borderRadius: 8 },
  switchTrack: {
    width: 42,
    height: 24,
    borderRadius: 24,
    padding: 3,
    borderWidth: 1,
    justifyContent: 'center',
  },
  switchThumb: { width: 16, height: 16, borderRadius: 16 },

  listStack: { gap: 10 },
  listRow: {
    minHeight: 58,
    borderRadius: 18,
    borderWidth: 1,
    paddingHorizontal: 14,
    paddingVertical: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  listContent: { flex: 1, gap: 3 },
  listTitle: { fontSize: 13, fontWeight: '800' },
  listSubtitle: { fontSize: 11, lineHeight: 15, fontWeight: '700' },

  tableShell: {
    borderRadius: 18,
    borderWidth: 1,
    overflow: 'hidden',
  },
  tableToolbar: {
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderBottomWidth: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
    flexWrap: 'wrap',
  },
  tableToolbarText: { fontSize: 12, fontWeight: '900' },
  tableHeader: {
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderBottomWidth: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  tableHeaderCell: { flex: 1, fontSize: 11, fontWeight: '900' },
  tableRow: {
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderBottomWidth: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  tableCell: { flex: 1, fontSize: 11, fontWeight: '700' },
  actionButton: {
    width: 30,
    height: 30,
    borderRadius: 10,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  footerRow: {
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderBottomWidth: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
    flexWrap: 'wrap',
  },

  statesGrid: { gap: 18 },
  statesGridWide: { flexDirection: 'row', alignItems: 'stretch' },
  statesGridStack: { flexDirection: 'column' },
  stateCanvas: {
    flex: 1,
    borderRadius: 24,
    borderWidth: 1,
    padding: 18,
    gap: 14,
    ...softShadow,
  },
  overlayCanvas: {
    minHeight: 200,
    borderRadius: 20,
    overflow: 'hidden',
    justifyContent: 'center',
  },
  overlayFill: { ...StyleSheet.absoluteFillObject },
  modalSheet: {
    marginHorizontal: 18,
    borderRadius: 20,
    borderWidth: 1,
    padding: 16,
    gap: 12,
  },
  loadingSheet: {
    marginHorizontal: 30,
    borderRadius: 18,
    borderWidth: 1,
    padding: 16,
    alignItems: 'center',
    gap: 10,
  },
  toastColumn: { flex: 1, gap: 12 },
  toastCard: {
    borderRadius: 18,
    borderWidth: 1,
    paddingHorizontal: 14,
    paddingVertical: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    ...softShadow,
  },
  toastTextWrap: { flex: 1, gap: 2 },
  toastTitle: { fontSize: 12, fontWeight: '900' },
  toastText: { fontSize: 11, lineHeight: 16, fontWeight: '700' },

  footerBar: {
    minHeight: 92,
    borderRadius: 24,
    borderWidth: 1,
    paddingHorizontal: 22,
    paddingVertical: 18,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 16,
    flexWrap: 'wrap',
    ...softShadow,
  },
  footerBrand: { gap: 4, minWidth: 220 },
  footerTitle: { fontSize: 16, fontWeight: '900' },
  footerCopy: { fontSize: 11, lineHeight: 16, fontWeight: '700' },
  footerLinks: { flexDirection: 'row', alignItems: 'center', gap: 16, flexWrap: 'wrap' },
  footerLinkText: { fontSize: 12, fontWeight: '900' },

  paletteSection: {
    borderRadius: 28,
    borderWidth: 1,
    padding: 20,
    gap: 18,
    ...elevatedShadow,
  },
  paletteHeader: { gap: 12 },
  paletteEyebrow: {
    fontSize: 10,
    fontWeight: '900',
    textTransform: 'uppercase',
    letterSpacing: 1.2,
  },
  paletteTitle: { fontSize: 28, lineHeight: 32, fontWeight: '900' },
  paletteText: { fontSize: 13, lineHeight: 20, fontWeight: '600', maxWidth: 940 },
  paletteSummaryRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
  paletteSummaryCard: {
    minWidth: 130,
    borderRadius: 18,
    borderWidth: 1,
    paddingHorizontal: 14,
    paddingVertical: 12,
    gap: 5,
  },
  paletteSummaryValue: { fontSize: 22, fontWeight: '900' },
  paletteSummaryLabel: { fontSize: 11, fontWeight: '800' },
  grid: { flexDirection: 'row', flexWrap: 'wrap', gap: 12 },

  groupCard: {
    minWidth: 280,
    flexBasis: '31%',
    flexGrow: 1,
    borderRadius: 22,
    borderWidth: 1,
    backgroundColor: '#FFFFFF',
    overflow: 'hidden',
    ...softShadow,
  },
  groupHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderBottomWidth: 1,
    backgroundColor: '#F8FAFC',
  },
  groupLabel: {
    fontSize: 10,
    fontWeight: '900',
    textTransform: 'uppercase',
    letterSpacing: 0.8,
    color: '#0F172A',
  },
  groupMeta: { fontSize: 10, fontWeight: '700', color: '#64748B' },
  groupBody: { padding: 12, gap: 10 },
  previewArea: {
    gap: 6,
    padding: 10,
    borderRadius: 14,
    backgroundColor: '#F8FAFC',
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  tokenGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 6 },

  swatchWrap: { width: 60, alignItems: 'center', gap: 4 },
  swatch: { width: 42, height: 18, borderRadius: 6, borderWidth: 1, borderColor: 'rgba(0,0,0,0.12)' },
  swatchTransparent: { backgroundColor: '#FFFFFF', borderStyle: 'dashed', borderColor: '#94A3B8' },
  swatchEmpty: { backgroundColor: '#F1F5F9', borderColor: '#CBD5E1', borderStyle: 'dashed' },
  swatchUndef: { backgroundColor: '#22C55E', borderColor: '#16A34A' },
  swatchLabel: { fontSize: 7, fontWeight: '700', color: '#64748B', textAlign: 'center' },
  swatchLabelUndef: { color: '#16A34A', fontWeight: '900' },

  tooltipWrap: {
    position: 'absolute',
    bottom: 34,
    left: -52,
    backgroundColor: '#0F172A',
    borderRadius: 10,
    padding: 8,
    width: 210,
    gap: 5,
    zIndex: 9999,
    ...Platform.select({ web: { boxShadow: '0 12px 26px rgba(0,0,0,0.38)', pointerEvents: 'none' } }),
  },
  tooltipRow: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  tooltipSwatch: { width: 10, height: 10, borderRadius: 3, borderWidth: 1, borderColor: '#475569', flexShrink: 0 },
  tooltipKey: { flex: 1, fontSize: 9, fontWeight: '700', color: '#94A3B8' },
  tooltipValue: { fontSize: 9, fontWeight: '900', color: '#FFFFFF' },

  undefinedZone: {
    backgroundColor: '#22C55E',
    borderColor: '#15803D',
  },

  loadingWrap: { minHeight: 320, alignItems: 'center', justifyContent: 'center' },
  emptyWrap: { padding: 40, alignItems: 'center', gap: 8 },
  emptyText: { fontSize: 13, fontWeight: '700', color: '#64748B', textAlign: 'center' },

  miniRow: { flexDirection: 'row', gap: 4, alignItems: 'center', flexWrap: 'wrap' },
  miniStack: { gap: 4 },
  miniBar: {
    minHeight: 22,
    borderRadius: 5,
    borderWidth: 1,
    paddingHorizontal: 7,
    paddingVertical: 3,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 5,
  },
  miniBarText: { fontSize: 9, fontWeight: '800' },
  miniCard: { borderRadius: 6, borderWidth: 1, overflow: 'hidden' },
  miniCardHeader: { paddingHorizontal: 7, paddingVertical: 3, borderBottomWidth: 1 },
  miniCardBody: { paddingHorizontal: 7, paddingVertical: 4 },
  miniText: { fontSize: 9, fontWeight: '700' },
  miniBtn: {
    paddingHorizontal: 7,
    paddingVertical: 4,
    borderRadius: 5,
    borderWidth: 1,
    alignItems: 'center',
    flexShrink: 0,
  },
  miniBtnText: { fontSize: 9, fontWeight: '800' },
  miniPill: { paddingHorizontal: 6, paddingVertical: 2, borderRadius: 999, borderWidth: 1 },
  miniPillText: { fontSize: 8, fontWeight: '800' },
  miniField: {
    borderRadius: 5,
    borderWidth: 1,
    paddingHorizontal: 6,
    paddingVertical: 3,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 4,
  },
  miniFieldText: { fontSize: 9, fontWeight: '700' },
  miniCheck: { width: 13, height: 13, borderRadius: 3, borderWidth: 1.5, alignItems: 'center', justifyContent: 'center' },
  miniCheckMark: { fontSize: 8, fontWeight: '900' },
  miniRadio: { width: 13, height: 13, borderRadius: 999, borderWidth: 1.5, alignItems: 'center', justifyContent: 'center' },
  miniRadioDot: { width: 5, height: 5, borderRadius: 999 },
  miniSwitch: { width: 26, height: 14, borderRadius: 999, padding: 2, justifyContent: 'center' },
  miniSwitchThumb: { width: 10, height: 10, borderRadius: 999 },
  miniListRow: { paddingHorizontal: 6, paddingVertical: 3, borderRadius: 4, borderWidth: 1, flexDirection: 'row', alignItems: 'center', gap: 4 },
  miniListText: { fontSize: 9, fontWeight: '700', flex: 1 },
  miniDivider: { height: 1, width: '100%' },
  miniOverlayShell: { height: 48, borderRadius: 6, overflow: 'hidden', justifyContent: 'center' },
  miniOverlayBackdrop: { ...StyleSheet.absoluteFillObject },
  miniOverlayCard: { marginHorizontal: 10, borderRadius: 6, borderWidth: 1, padding: 5, alignItems: 'center', gap: 3 },
  miniToastRow: { borderRadius: 5, borderWidth: 1, paddingHorizontal: 6, paddingVertical: 3, flexDirection: 'row', alignItems: 'center', gap: 4 },
  miniToastText: { fontSize: 8, fontWeight: '700' },
  miniIconBubble: { width: 20, height: 20, borderRadius: 5, alignItems: 'center', justifyContent: 'center' },
  miniTableHeader: { flexDirection: 'row', gap: 4, paddingHorizontal: 5, paddingVertical: 3, borderBottomWidth: 1 },
  miniTableRow: { flexDirection: 'row', gap: 4, paddingHorizontal: 5, paddingVertical: 3, borderBottomWidth: 1 },
  miniTableCell: { flex: 1, fontSize: 8, fontWeight: '700' },
  miniSurface: { borderRadius: 6, borderWidth: 1, padding: 5, gap: 3 },
  miniLinkText: { fontSize: 9, fontWeight: '800' },
  miniNavItem: { paddingHorizontal: 7, paddingVertical: 3, borderRadius: 4, borderWidth: 1, flexDirection: 'row', alignItems: 'center', gap: 4 },
  miniNavText: { fontSize: 9, fontWeight: '700' },
});

export default styles;
