import { Platform, StyleSheet } from 'react-native';

const cardShadow = Platform.select({
  ios: {
    shadowColor: '#1a1a1a',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.08,
    shadowRadius: 16,
  },
  android: { elevation: 3 },
  web: { boxShadow: '0 8px 24px rgba(15,23,42,0.08)' },
});

const themeCardShadow = Platform.select({
  ios: {
    shadowColor: '#0f172a',
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.12,
    shadowRadius: 22,
  },
  android: { elevation: 5 },
  web: { boxShadow: '0 14px 32px rgba(15,23,42,0.12)' },
});

const styles = StyleSheet.create({
  root: { flex: 1 },
  scroll: { padding: 16, paddingBottom: 40, gap: 16 },
  toolbar: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  createButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 12,
  },
  createButtonText: {
    color: '#FFFFFF',
    fontSize: 13,
    fontWeight: '800',
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: '800',
    color: '#1a1a1a',
  },
  sectionText: {
    fontSize: 13,
    lineHeight: 20,
    color: '#777777',
    marginTop: 4,
  },
  loadingWrap: {
    minHeight: 220,
    alignItems: 'center',
    justifyContent: 'center',
  },
  emptyCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    padding: 22,
    alignItems: 'center',
    gap: 10,
    ...cardShadow,
  },
  emptyTitle: {
    fontSize: 16,
    fontWeight: '800',
    color: '#1a1a1a',
    textAlign: 'center',
  },
  emptyText: {
    fontSize: 13,
    lineHeight: 20,
    color: '#777777',
    textAlign: 'center',
  },
  themeList: { gap: 28 },
  themeCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    padding: 16,
    gap: 14,
    ...themeCardShadow,
  },
  themeRowTop: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: 12,
  },
  themeTitleWrap: {
    flex: 1,
    gap: 4,
  },
  themeName: {
    fontSize: 16,
    fontWeight: '800',
    color: '#1a1a1a',
  },
  themeActions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    justifyContent: 'flex-end',
  },
  actionButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#d7d7d7',
    backgroundColor: '#F8FAFC',
  },
  actionButtonText: {
    fontSize: 12,
    fontWeight: '800',
    color: '#1a1a1a',
  },
  themeMetaText: {
    fontSize: 12,
    color: '#777777',
    fontWeight: '700',
  },
  colorTileGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  colorTile: {
    minHeight: 34,
    minWidth: 112,
    flexBasis: '23%',
    flexGrow: 1,
    borderRadius: 12,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderWidth: 1,
    justifyContent: 'center',
  },
  colorTileLabel: {
    fontSize: 12,
    fontWeight: '800',
  },
  iconButton: {
    width: 38,
    height: 38,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#cccccc',
    backgroundColor: '#F8FAFC',
  },
  backdrop: {
    flex: 1,
    backgroundColor: 'rgba(15,23,42,0.48)',
    justifyContent: 'flex-end',
  },
  modalSheet: {
    backgroundColor: '#FFFFFF',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    minHeight: 260,
    maxHeight: '92%',
    padding: 16,
    gap: 14,
    ...cardShadow,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 12,
  },
  modalTitle: {
    flex: 1,
    fontSize: 18,
    fontWeight: '800',
    color: '#1a1a1a',
  },
  modalSubtitle: {
    fontSize: 13,
    lineHeight: 20,
    color: '#777777',
  },
  formField: { gap: 8 },
  formLabel: {
    fontSize: 12,
    fontWeight: '800',
    color: '#475569',
    textTransform: 'uppercase',
    letterSpacing: 0.4,
  },
  textInput: {
    height: 46,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#cccccc',
    paddingHorizontal: 12,
    fontSize: 14,
    fontWeight: '600',
    color: '#1a1a1a',
    backgroundColor: '#FFFFFF',
  },
  helperText: {
    fontSize: 12,
    lineHeight: 18,
    color: '#777777',
  },
  colorEditor: {
    gap: 10,
    padding: 14,
    borderRadius: 16,
    backgroundColor: '#F8FAFC',
    borderWidth: 1,
    borderColor: '#cccccc',
  },
  colorEditorHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 10,
  },
  colorEditorLabel: {
    fontSize: 14,
    fontWeight: '800',
    color: '#1a1a1a',
  },
  colorPreview: {
    width: 34,
    height: 34,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: '#cccccc',
  },
  swatchPicker: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  pickerButton: {
    width: 30,
    height: 30,
    borderRadius: 10,
    borderWidth: 2,
    borderColor: 'transparent',
  },
  pickerButtonActive: {
    borderColor: '#1a1a1a',
  },
  colorInputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  colorInput: {
    flex: 1,
    height: 42,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#cccccc',
    paddingHorizontal: 12,
    fontSize: 14,
    fontWeight: '700',
    color: '#1a1a1a',
    backgroundColor: '#FFFFFF',
  },
  colorHint: {
    fontSize: 12,
    fontWeight: '700',
    color: '#777777',
  },
  modalActions: {
    flexDirection: 'row',
    gap: 10,
    paddingTop: 8,
  },
  secondaryButton: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 14,
    borderRadius: 12,
    borderWidth: 1.5,
    borderColor: '#cccccc',
    backgroundColor: '#FFFFFF',
  },
  secondaryButtonText: {
    fontSize: 14,
    fontWeight: '800',
    color: '#1a1a1a',
  },
  primaryButton: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 14,
    borderRadius: 12,
  },
  primaryButtonText: {
    fontSize: 14,
    fontWeight: '800',
    color: '#FFFFFF',
  },
});

export default styles;
