import Formatter from '@controleonline/ui-common/src/utils/formatter.js';
import {
  formatArgumentsValue,
  formatBooleanValue,
  formatCommandValue,
  formatEnabledValue,
  formatLastStatusValue,
  saveArgumentsValue,
  saveBooleanValue,
  saveCommandValue,
} from './formatters';

export const cronJobColumns = [
  {
    editable: false,
    isIdentity: true,
    sortable: true,
    name: 'id',
    align: 'left',
    label: 'ID',
    format: value => `#${value}`,
  },
  {
    editable: true,
    sortable: true,
    name: 'title',
    align: 'left',
    label: 'Título',
  },
  {
    editable: true,
    sortable: true,
    name: 'command',
    align: 'left',
    label: 'Command',
    list: 'cron_job_commands/getItems',
    searchParam: 'name',
    formatList: formatCommandValue,
    saveFormat: saveCommandValue,
    format: value => String(value ?? '').trim(),
  },
  {
    editable: true,
    sortable: true,
    name: 'cronExpression',
    align: 'left',
    label: 'Cron',
    defaultValue: '* * * * *',
    format: value => String(value ?? '').trim(),
  },
  {
    editable: false,
    sortable: false,
    name: 'lastExecution',
    align: 'left',
    label: 'Última execução',
    format: value => {
      const formatted = Formatter.formatDateYmdTodmY(value, true);
      return String(formatted || '').trim() || '—';
    },
  },
  {
    editable: false,
    sortable: false,
    name: 'lastStatus',
    align: 'left',
    label: 'Último status',
    format: formatLastStatusValue,
  },
  {
    editable: true,
    sortable: true,
    name: 'enabled',
    align: 'left',
    label: 'Ativo',
    defaultValue: true,
    list: [
      {value: true, label: 'Sim'},
      {value: false, label: 'Não'},
    ],
    formatList: formatBooleanValue,
    saveFormat: saveBooleanValue,
    format: formatEnabledValue,
  },
  {
    editable: true,
    sortable: false,
    table: false,
    name: 'arguments',
    align: 'left',
    label: 'Argumentos',
    editFormat: formatArgumentsValue,
    format: formatArgumentsValue,
    saveFormat: saveArgumentsValue,
  },
  {
    editable: true,
    sortable: false,
    table: false,
    name: 'description',
    align: 'left',
    label: 'Descrição',
    format: value => String(value ?? '').trim(),
  },
  {
    editable: false,
    sortable: false,
    name: 'isValid',
    align: 'left',
    label: 'Válido',
    format: value => (value ? 'Sim' : 'Não'),
  },
];
