import { StyleSheet } from 'react-native';

export const SCREEN_COLORS = {
  background: '#0B1220',
  panel: '#111B2F',
  panelAlt: '#16233B',
  border: '#24324A',
  text: '#EEF4FF',
  muted: '#9AA9C2',
  brand: '#FBBF24',
  good: '#22C55E',
  warn: '#F97316',
  bad: '#EF4444',
  chip: '#1C2942',
};

export default StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: SCREEN_COLORS.background,
  },
  loadingContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: SCREEN_COLORS.background,
  },
  scrollContent: {
    paddingHorizontal: 16,
    paddingTop: 14,
    paddingBottom: 28,
  },
  heroCard: {
    borderRadius: 26,
    borderWidth: 1,
    borderColor: SCREEN_COLORS.border,
    backgroundColor: SCREEN_COLORS.panel,
    padding: 20,
    marginBottom: 18,
    overflow: 'hidden',
  },
  heroAccent: {
    position: 'absolute',
    right: -24,
    top: -24,
    width: 120,
    height: 120,
    borderRadius: 60,
    opacity: 0.16,
  },
  heroEyebrow: {
    fontSize: 12,
    fontWeight: '700',
    letterSpacing: 1.2,
    textTransform: 'uppercase',
    color: SCREEN_COLORS.brand,
    marginBottom: 10,
  },
  heroTitle: {
    color: SCREEN_COLORS.text,
    fontSize: 28,
    fontWeight: '800',
    marginBottom: 8,
  },
  heroSubtitle: {
    color: SCREEN_COLORS.muted,
    fontSize: 14,
    lineHeight: 20,
    marginBottom: 14,
    maxWidth: 780,
  },
  heroBadgeRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginHorizontal: -4,
  },
  heroBadge: {
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: 12,
    paddingVertical: 7,
    marginHorizontal: 4,
    marginBottom: 8,
    backgroundColor: SCREEN_COLORS.chip,
  },
  heroBadgeText: {
    color: SCREEN_COLORS.text,
    fontSize: 12,
    fontWeight: '700',
  },
  companyLine: {
    color: SCREEN_COLORS.text,
    fontSize: 13,
    fontWeight: '700',
    marginBottom: 2,
  },
  tabScroll: {
    marginBottom: 14,
  },
  tabRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 4,
  },
  tabButton: {
    borderRadius: 18,
    borderWidth: 1,
    borderColor: SCREEN_COLORS.border,
    backgroundColor: SCREEN_COLORS.panel,
    paddingHorizontal: 15,
    paddingVertical: 12,
    marginRight: 10,
    minWidth: 150,
  },
  tabButtonActive: {
    borderColor: SCREEN_COLORS.brand,
    backgroundColor: '#1C2942',
  },
  tabLabel: {
    color: SCREEN_COLORS.text,
    fontSize: 14,
    fontWeight: '700',
    marginBottom: 3,
  },
  tabDescription: {
    color: SCREEN_COLORS.muted,
    fontSize: 11,
    lineHeight: 15,
  },
  sectionBlock: {
    borderRadius: 24,
    borderWidth: 1,
    borderColor: SCREEN_COLORS.border,
    backgroundColor: SCREEN_COLORS.panel,
    padding: 16,
    marginBottom: 16,
  },
  sectionHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  sectionTitleWrap: {
    flex: 1,
    marginRight: 12,
  },
  sectionTitle: {
    color: SCREEN_COLORS.text,
    fontSize: 18,
    fontWeight: '800',
    marginBottom: 3,
  },
  sectionDescription: {
    color: SCREEN_COLORS.muted,
    fontSize: 12,
    lineHeight: 18,
  },
  modeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
  },
  modeButton: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: SCREEN_COLORS.border,
    backgroundColor: SCREEN_COLORS.chip,
    paddingHorizontal: 12,
    paddingVertical: 8,
    marginLeft: 8,
    marginBottom: 6,
  },
  modeButtonActive: {
    borderColor: SCREEN_COLORS.brand,
  },
  modeButtonText: {
    color: SCREEN_COLORS.text,
    fontSize: 12,
    fontWeight: '700',
  },
  metricGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginHorizontal: -6,
    marginBottom: 4,
  },
  metricCard: {
    position: 'relative',
    minWidth: 160,
    flexGrow: 1,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: SCREEN_COLORS.border,
    backgroundColor: SCREEN_COLORS.panelAlt,
    padding: 14,
    marginHorizontal: 6,
    marginBottom: 12,
  },
  metricValue: {
    color: SCREEN_COLORS.text,
    fontSize: 26,
    fontWeight: '800',
    marginBottom: 6,
  },
  metricLabel: {
    color: SCREEN_COLORS.muted,
    fontSize: 12,
    lineHeight: 18,
  },
  metricHelperText: {
    color: SCREEN_COLORS.muted,
    fontSize: 11,
    lineHeight: 16,
    marginTop: 4,
  },
  metricActionIcon: {
    position: 'absolute',
    top: 12,
    right: 12,
  },
  twoColumnRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginHorizontal: -6,
  },
  sidePanel: {
    minWidth: 280,
    flexGrow: 1,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: SCREEN_COLORS.border,
    backgroundColor: SCREEN_COLORS.panelAlt,
    padding: 14,
    marginHorizontal: 6,
    marginBottom: 12,
  },
  panelTitle: {
    color: SCREEN_COLORS.text,
    fontSize: 15,
    fontWeight: '700',
    marginBottom: 10,
  },
  listItemCard: {
    borderRadius: 16,
    borderWidth: 1,
    borderColor: SCREEN_COLORS.border,
    backgroundColor: SCREEN_COLORS.chip,
    padding: 12,
    marginBottom: 10,
  },
  listItemHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    marginBottom: 6,
  },
  listItemTitle: {
    color: SCREEN_COLORS.text,
    fontSize: 14,
    fontWeight: '700',
    flex: 1,
    marginRight: 8,
  },
  listItemMeta: {
    color: SCREEN_COLORS.muted,
    fontSize: 12,
    lineHeight: 17,
  },
  splitLayout: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginHorizontal: -6,
  },
  splitPrimary: {
    minWidth: 320,
    flexGrow: 1.25,
    marginHorizontal: 6,
    marginBottom: 12,
  },
  splitSecondary: {
    minWidth: 280,
    flexGrow: 1,
    marginHorizontal: 6,
    marginBottom: 12,
  },
  filterRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'center',
    marginBottom: 14,
  },
  filterChip: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: SCREEN_COLORS.border,
    backgroundColor: SCREEN_COLORS.chip,
    paddingHorizontal: 12,
    paddingVertical: 8,
    marginRight: 8,
    marginBottom: 8,
  },
  filterChipText: {
    color: SCREEN_COLORS.text,
    fontSize: 12,
    fontWeight: '700',
  },
  filterChipActive: {
    borderColor: SCREEN_COLORS.brand,
    backgroundColor: '#263557',
  },
  searchInput: {
    minHeight: 42,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: SCREEN_COLORS.border,
    backgroundColor: SCREEN_COLORS.chip,
    color: SCREEN_COLORS.text,
    fontSize: 13,
    paddingHorizontal: 14,
    marginBottom: 12,
  },
  tableWrap: {
    borderRadius: 18,
    borderWidth: 1,
    borderColor: SCREEN_COLORS.border,
    backgroundColor: SCREEN_COLORS.panelAlt,
    overflow: 'hidden',
  },
  tableHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#0F172A',
    borderBottomWidth: 1,
    borderBottomColor: SCREEN_COLORS.border,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  tableHeaderCell: {
    color: SCREEN_COLORS.muted,
    fontSize: 11,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 0.6,
  },
  tableRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: SCREEN_COLORS.border,
  },
  tableRowActive: {
    backgroundColor: '#1B2843',
  },
  tableCellText: {
    color: SCREEN_COLORS.text,
    fontSize: 13,
    lineHeight: 18,
  },
  mutedText: {
    color: SCREEN_COLORS.muted,
    fontSize: 12,
    lineHeight: 18,
  },
  pill: {
    alignSelf: 'flex-start',
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  pillText: {
    color: SCREEN_COLORS.text,
    fontSize: 11,
    fontWeight: '700',
  },
  detailCard: {
    borderRadius: 18,
    borderWidth: 1,
    borderColor: SCREEN_COLORS.border,
    backgroundColor: SCREEN_COLORS.panelAlt,
    padding: 16,
  },
  detailHeader: {
    marginBottom: 14,
  },
  detailTitle: {
    color: SCREEN_COLORS.text,
    fontSize: 22,
    fontWeight: '800',
    marginBottom: 6,
  },
  detailSubtitle: {
    color: SCREEN_COLORS.muted,
    fontSize: 13,
    lineHeight: 18,
    marginBottom: 8,
  },
  badgesWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginHorizontal: -4,
    marginBottom: 6,
  },
  badge: {
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: 10,
    paddingVertical: 6,
    marginHorizontal: 4,
    marginBottom: 8,
    backgroundColor: SCREEN_COLORS.chip,
  },
  badgeText: {
    color: SCREEN_COLORS.text,
    fontSize: 11,
    fontWeight: '700',
  },
  divider: {
    height: 1,
    backgroundColor: SCREEN_COLORS.border,
    marginVertical: 14,
  },
  fieldGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginHorizontal: -6,
  },
  fieldCard: {
    minWidth: 150,
    flexGrow: 1,
    borderRadius: 15,
    borderWidth: 1,
    borderColor: SCREEN_COLORS.border,
    backgroundColor: SCREEN_COLORS.chip,
    padding: 12,
    marginHorizontal: 6,
    marginBottom: 12,
  },
  fieldLabel: {
    color: SCREEN_COLORS.muted,
    fontSize: 11,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    marginBottom: 6,
  },
  fieldValue: {
    color: SCREEN_COLORS.text,
    fontSize: 14,
    lineHeight: 19,
    fontWeight: '600',
  },
  detailSectionTitle: {
    color: SCREEN_COLORS.text,
    fontSize: 14,
    fontWeight: '700',
    marginBottom: 10,
  },
  smallListItem: {
    borderRadius: 14,
    borderWidth: 1,
    borderColor: SCREEN_COLORS.border,
    backgroundColor: SCREEN_COLORS.chip,
    padding: 11,
    marginBottom: 8,
  },
  smallListTitle: {
    color: SCREEN_COLORS.text,
    fontSize: 13,
    fontWeight: '700',
    marginBottom: 3,
  },
  smallListMeta: {
    color: SCREEN_COLORS.muted,
    fontSize: 12,
    lineHeight: 17,
  },
  missingBlock: {
    borderRadius: 16,
    borderWidth: 1,
    padding: 12,
    backgroundColor: '#3A1318',
  },
  missingLabel: {
    fontSize: 11,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 0.6,
    marginBottom: 4,
  },
  missingText: {
    fontSize: 13,
    fontWeight: '700',
    lineHeight: 18,
  },
  emptyBlock: {
    borderRadius: 16,
    borderWidth: 1,
    borderColor: SCREEN_COLORS.border,
    backgroundColor: SCREEN_COLORS.chip,
    padding: 14,
  },
  emptyText: {
    color: SCREEN_COLORS.muted,
    fontSize: 13,
    lineHeight: 19,
  },
  registerGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginHorizontal: -6,
  },
  registerCard: {
    minWidth: 240,
    flexGrow: 1,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: SCREEN_COLORS.border,
    backgroundColor: SCREEN_COLORS.panelAlt,
    padding: 14,
    marginHorizontal: 6,
    marginBottom: 12,
  },
  registerCardHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  registerActionsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    flexWrap: 'wrap',
    marginHorizontal: -4,
    marginVertical: -4,
  },
  registerActionWrap: {
    marginHorizontal: 4,
    marginVertical: 4,
  },
  registerCardTitle: {
    color: SCREEN_COLORS.text,
    fontSize: 15,
    fontWeight: '700',
  },
  registerCount: {
    color: SCREEN_COLORS.brand,
    fontSize: 28,
    fontWeight: '800',
    marginBottom: 8,
  },
  registerPreview: {
    color: SCREEN_COLORS.muted,
    fontSize: 12,
    lineHeight: 18,
  },
  actionButton: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'flex-start',
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: 10,
    paddingVertical: 7,
    backgroundColor: SCREEN_COLORS.chip,
  },
  actionButtonText: {
    color: SCREEN_COLORS.text,
    fontSize: 12,
    fontWeight: '700',
    marginLeft: 6,
  },
  smallListHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 3,
  },
  smallListAction: {
    flexDirection: 'row',
    alignItems: 'center',
    marginLeft: 8,
  },
  smallListActionText: {
    color: SCREEN_COLORS.brand,
    fontSize: 11,
    fontWeight: '700',
    marginLeft: 4,
  },
  errorCard: {
    borderRadius: 18,
    borderWidth: 1,
    borderColor: SCREEN_COLORS.bad,
    backgroundColor: '#3A1318',
    padding: 16,
    marginBottom: 16,
  },
  errorTitle: {
    color: '#FCA5A5',
    fontSize: 15,
    fontWeight: '700',
    marginBottom: 6,
  },
  errorText: {
    color: '#FECACA',
    fontSize: 13,
    lineHeight: 19,
  },
  refreshButton: {
    marginTop: 10,
    alignSelf: 'flex-start',
    borderRadius: 999,
    borderWidth: 1,
    borderColor: '#FCA5A5',
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  refreshButtonText: {
    color: '#FECACA',
    fontSize: 12,
    fontWeight: '700',
  },
});
