export const CATEGORY_IMAGE_ASSETS = {
  cat_gyros: require('./assets/categories/gyros-da-casa.png'),
  cat_combos: require('./assets/categories/capa-categoria-combos.png'),
  cat_batatas: require('./assets/categories/batatas-fritas.png'),
  cat_gratinados: require('./assets/categories/gratinados.png'),
  cat_almoco: require('./assets/categories/almoco-executivo.png'),
  cat_molhos: require('./assets/categories/molhos-e-vinagrete-a-parte.png'),
  cat_sobremesas: require('./assets/categories/sobremesas.png'),
  cat_bebidas: require('./assets/categories/bebidas.png'),
};

export const PRODUCT_IMAGE_ASSETS = {
  prd_alpha: require('./assets/products/gyr-lan-alpha.png'),
  prd_beta: require('./assets/products/gyr-lan-beta.png'),
  prd_gamma: require('./assets/products/gyr-lan-gamma.png'),
  prd_vegetariano: require('./assets/products/gyr-lan-veg.png'),
  prd_combo3_alpha: require('./assets/products/gyr-cmb3-alpha.png'),
  prd_combo3_beta: require('./assets/products/gyr-cmb3-beta.png'),
  prd_combo3_gamma: require('./assets/products/gyr-cmb3-gamma.png'),
  prd_combo3_delta: require('./assets/products/gyr-cmb3-veg.png'),
  prd_combo1: require('./assets/products/gyr-cmb3-alpha.png'),
  prd_combo2: require('./assets/products/gyr-cmb3-beta.png'),
  prd_combo3: require('./assets/products/gyr-cmb3-gamma.png'),
  prd_bat_p: require('./assets/products/gyr-bat-frt-m200.png'),
  prd_bat_g: require('./assets/products/gyr-bat-frt-g400.png'),
  prd_prot_grat_m: require('./assets/products/gyr-grt-prot-m.png'),
  prd_carne_grat: require('./assets/products/gyr-grt-prot-g.png'),
  prd_bat_grat_p: require('./assets/products/gyr-bat-grt-m100.png'),
  prd_bat_grat_g: require('./assets/products/gyr-bat-grt-g220.png'),
  prd_prato_alpha: require('./assets/products/gyr-alm-alpha.png'),
  prd_prato_beta: require('./assets/products/gyr-alm-beta.png'),
  prd_prato_gamma: require('./assets/products/gyr-alm-gamma.png'),
  prd_prato_veg: require('./assets/products/gyr-alm-veg.png'),
  prd_molho_extra: require('./assets/products/gyr-mol-maigrl-60.png'),
  prd_maionese_defumada_extra: require('./assets/products/gyr-mol-maigrl-60.png'),
  prd_maionese_verde_extra: require('./assets/products/gyr-mol-maivrd-60.png'),
  prd_maionese_chimichurri_extra: require('./assets/products/gyr-mol-maichm-60.png'),
  prd_barbecue_extra: require('./assets/products/gyr-mol-bbq-60.png'),
  prd_vinagrete_extra: require('./assets/products/gyr-mol-vin-60.png'),
  prd_churros: require('./assets/products/gyr-sob-chu-6un.png'),
  prd_agua_gas_510: require('./assets/products/gyr-beb-aguagas-510.webp'),
  prd_agua_510: require('./assets/products/gyr-beb-agua-510.webp'),
  prd_coca: require('./assets/products/gyr-beb-coca-350.jpg'),
  prd_coca_zero: require('./assets/products/gyr-beb-cocaz-350.webp'),
  prd_guarana_350: require('./assets/products/gyr-beb-guar-350.jpg'),
  prd_fanta: require('./assets/products/gyr-beb-fanta-350.webp'),
  prd_schweppes_350: require('./assets/products/gyr-beb-schw-350.webp'),
  prd_sprite_350: require('./assets/products/gyr-beb-spr-350.png'),
  prd_ice_tea_limao_450: require('./assets/products/gyr-beb-itea-lim-450.jpg'),
  prd_ice_tea_pessego_450: require('./assets/products/gyr-beb-itea-pes-450.jpg'),
  prd_bud_330: require('./assets/products/gyr-beb-bud-330.jpg'),
  prd_heineken_330: require('./assets/products/gyr-beb-hei-330.webp'),
  prd_h2o_500: require('./assets/products/gyr-beb-h2o-500.jpg'),
  prd_limoneto_500: require('./assets/products/gyr-beb-limo-500.webp'),
  prd_delvalle_uva_290: require('./assets/products/gyr-beb-dvuva-290.webp'),
  prd_coca_2l: require('./assets/products/gyr-beb-coca-2000.webp'),
};

export const RESOURCE_IMAGE_ASSETS = {
  'ingredient:ing_fraldinha': require('./assets/products/gyr-add-fraldinha.png'),
  'ingredient:ing_frango': require('./assets/products/gyr-add-frango.png'),
  'ingredient:ing_linguica': require('./assets/products/gyr-add-linguica.png'),
  'recipe:rec_fraldinha_preparada': require('./assets/products/gyr-add-fraldinha.png'),
  'recipe:rec_frango_preparado': require('./assets/products/gyr-add-frango.png'),
  'recipe:rec_linguica_preparada': require('./assets/products/gyr-add-linguica.png'),
  'recipe:rec_berinjela_antepasto': require('./assets/products/gyr-add-berinjela.png'),
  'ingredient:ing_bacon_cubos': require('./assets/products/gyr-add-bacon.png'),
  'ingredient:ing_mucarela': require('./assets/products/gyr-add-mucarela-gratinada.png'),
  'recipe:rec_grat_muc': require('./assets/products/gyr-add-mucarela-gratinada.png'),
  'recipe:rec_grat_muc_p': require('./assets/products/gyr-add-mucarela-gratinada.png'),
  'recipe:rec_grat_muc_g': require('./assets/products/gyr-add-mucarela-gratinada.png'),
  'ingredient:ing_catupiry': require('./assets/products/gyr-add-catupiry-original.png'),
  'recipe:rec_grat_cat': require('./assets/products/gyr-add-catupiry-original.png'),
  'recipe:rec_grat_cat_p': require('./assets/products/gyr-add-catupiry-original.png'),
  'recipe:rec_grat_cat_g': require('./assets/products/gyr-add-catupiry-original.png'),
  'ingredient:ing_4queijos': require('./assets/products/gyr-add-catupiry-4q.png'),
  'recipe:rec_grat_4q': require('./assets/products/gyr-add-catupiry-4q.png'),
  'recipe:rec_grat_4q_p': require('./assets/products/gyr-add-catupiry-4q.png'),
  'recipe:rec_grat_4q_g': require('./assets/products/gyr-add-catupiry-4q.png'),
  'ingredient:ing_cheddar': require('./assets/products/gyr-add-cheddar-polenghi.png'),
  'recipe:rec_grat_cheddar': require('./assets/products/gyr-add-cheddar-polenghi.png'),
  'recipe:rec_grat_cheddar_p': require('./assets/products/gyr-add-cheddar-polenghi.png'),
  'recipe:rec_grat_cheddar_g': require('./assets/products/gyr-add-cheddar-polenghi.png'),
  'ingredient:ing_saches_mix': require('./assets/products/gyr-mol-saches-5un.png'),
  'ingredient:ing_maionese_junior_grill': require('./assets/products/gyr-mol-maigrl-60.png'),
  'recipe:rec_maionese': require('./assets/products/gyr-mol-maigrl-60.png'),
  'recipe:rec_maionese_defumada': require('./assets/products/gyr-mol-maigrl-60.png'),
  'product:prd_sache5': require('./assets/products/gyr-mol-saches-5un.png'),
};

export const ADDON_IMAGE_ASSETS = {
  bacon: require('./assets/products/gyr-add-bacon.png'),
  mucarela: require('./assets/products/gyr-add-mucarela-gratinada.png'),
  muçarela: require('./assets/products/gyr-add-mucarela-gratinada.png'),
  catupiry_4q: require('./assets/products/gyr-add-catupiry-4q.png'),
  '4_queijos': require('./assets/products/gyr-add-catupiry-4q.png'),
  catupiry: require('./assets/products/gyr-add-catupiry-original.png'),
  cheddar: require('./assets/products/gyr-add-cheddar-polenghi.png'),
  fraldinha: require('./assets/products/gyr-add-fraldinha.png'),
  frango: require('./assets/products/gyr-add-frango.png'),
  linguica: require('./assets/products/gyr-add-linguica.png'),
  linguiça: require('./assets/products/gyr-add-linguica.png'),
  berinjela: require('./assets/products/gyr-add-berinjela.png'),
  saches: require('./assets/products/gyr-mol-saches-5un.png'),
  sachês: require('./assets/products/gyr-mol-saches-5un.png'),
  maionese_da_casa: require('./assets/products/gyr-mol-maigrl-60.png'),
  maionese_defumada: require('./assets/products/gyr-mol-maigrl-60.png'),
};
