import {Platform, StyleSheet} from 'react-native';

const shadow = color =>
  Platform.select({
    android: {elevation: 2},
    ios: {
      shadowColor: color,
      shadowOffset: {width: 0, height: 4},
      shadowOpacity: 0.08,
      shadowRadius: 12,
    },
    web: {boxShadow: `0 4px 16px ${color}22`},
  });

export const createStyles = palette =>
  StyleSheet.create({
    container: {flex: 1, backgroundColor: palette.background},
    content: {
      paddingHorizontal: 20,
      paddingTop: 20,
      paddingBottom: 36,
      width: '100%',
      maxWidth: 1120,
      alignSelf: 'center',
    },
    hero: {
      backgroundColor: palette.primary,
      borderRadius: 18,
      padding: 20,
      marginBottom: 18,
    },
    heroEyebrow: {
      color: palette.white,
      fontSize: 12,
      fontWeight: '700',
      marginBottom: 6,
      textTransform: 'uppercase',
    },
    heroTitle: {color: palette.white, fontSize: 24, fontWeight: '800'},
    heroText: {color: palette.white, fontSize: 14, lineHeight: 20, marginTop: 8},
    draftNotice: {
      backgroundColor: palette.warningBackground || '#FEF3C7',
      borderColor: palette.warning || '#F59E0B',
      borderRadius: 12,
      borderWidth: 1,
      marginBottom: 18,
      padding: 12,
    },
    draftNoticeText: {color: palette.text, fontSize: 13, lineHeight: 18},
    layout: {flexDirection: 'row', flexWrap: 'wrap', gap: 18},
    formColumn: {flex: 1, minWidth: 300},
    stepsColumn: {flex: 1, minWidth: 300},
    card: {
      backgroundColor: palette.cardBackground || palette.white,
      borderColor: palette.border,
      borderRadius: 16,
      borderWidth: 1,
      padding: 18,
      ...shadow(palette.text),
    },
    cardTitle: {color: palette.text, fontSize: 18, fontWeight: '800'},
    cardText: {color: palette.textSecondary, fontSize: 13, lineHeight: 19, marginTop: 6},
    field: {marginTop: 16},
    label: {color: palette.text, fontSize: 13, fontWeight: '700', marginBottom: 6},
    input: {
      backgroundColor: palette.white,
      borderColor: palette.border,
      borderRadius: 10,
      borderWidth: 1,
      color: palette.text,
      fontSize: 14,
      minHeight: 44,
      paddingHorizontal: 12,
      paddingVertical: 10,
    },
    readOnlyInput: {backgroundColor: palette.background, color: palette.textSecondary},
    notesInput: {minHeight: 88, textAlignVertical: 'top'},
    fieldRow: {flexDirection: 'row', flexWrap: 'wrap', gap: 12},
    fieldHalf: {flex: 1, minWidth: 130},
    button: {
      alignItems: 'center',
      backgroundColor: palette.primary,
      borderRadius: 12,
      marginTop: 20,
      paddingHorizontal: 18,
      paddingVertical: 13,
    },
    buttonDisabled: {opacity: 0.45},
    buttonText: {color: palette.white, fontSize: 14, fontWeight: '800'},
    successBox: {
      backgroundColor: palette.successBackground || '#DCFCE7',
      borderColor: palette.success || '#16A34A',
      borderRadius: 10,
      borderWidth: 1,
      marginTop: 14,
      padding: 12,
    },
    successText: {color: palette.text, fontSize: 13, fontWeight: '700'},
    stepsList: {gap: 8, marginTop: 16},
    step: {
      alignItems: 'center',
      backgroundColor: palette.background,
      borderColor: palette.border,
      borderRadius: 10,
      borderWidth: 1,
      flexDirection: 'row',
      padding: 10,
    },
    stepIndex: {
      alignItems: 'center',
      backgroundColor: palette.primary,
      borderRadius: 9,
      height: 28,
      justifyContent: 'center',
      marginRight: 10,
      width: 28,
    },
    stepIndexText: {color: palette.white, fontSize: 12, fontWeight: '800'},
    stepBody: {flex: 1},
    stepLabel: {color: palette.text, fontSize: 13, fontWeight: '700'},
    stepStatus: {color: palette.textSecondary, fontSize: 11, marginTop: 2},
    activeStatus: {color: palette.primary, fontWeight: '800'},
  });

export default createStyles;
